### PR TITLE
f/402 fix plugin editor crashing for new databases

### LINKED ISSUE #402: Plugin Editor Crashes when new database is added
**Please describe the bug:**  
Plugin Editor Crashes when new a database is added. This has to do with the dynamic adding of settings, because the new database can't be resolved in the settings map.

Error: TypeError: Cannot read property 'Compression' of undefined

simply throwing the event does not help.

**Please describe steps to reproduce:**  
1. add new db
2. click on Plugins
Error

**What is the expected behavior? Please describe:**  
The new database should be added normally, plugins and settings should be updated.

### PR DESCRIPTION
**Pull request by MaxSchneider1337**
# Resolves #402

**Does your pull request solve a problem? Please describe:**  
plugin editor crashing for new databases

**Affected Component(s):**  
Plugin Frontend

### CODE REVIEW

**Review by schTi — APPROVED** [review]
nice one

**Review by schTi — CHANGES_REQUESTED** [review]
you should test if it really will fix the bug

**Comment by MaxSchneider1337** [comment]
> you should test if it really will fix the bug

I think this should be fixed... tried nearly everything and it works.

**Review by schTi — APPROVED** [review]
Ok cool

**Pull request merged**
