### PR TITLE
F/521 improve navigationbar design

### LINKED ISSUE #521: remove whitespace from navbar
**Is your feature request related to a problem? Please describe:**  
The navigation bar still has too much whitespace and needs some design improvement.

**Please describe the solution you'd like:**  
Delete whitespace and change desing on navbar. 

**Affected Component(s):**  
`Frontend`

**Additional context:**

### PR DESCRIPTION
**Pull request by monasobh**
# Resolves #521 

**Does your pull request solve a problem? Please describe:**  
Delete whitespace from navbar and change design (icons, naming etc.).

**Affected Component(s):**  
`Frontend`

Before:
comparison_before

What has changed: 
1. Views --> Analysis Views
2. Background bright grey 
~3. Edited space between lines and made them a little shorter~
4. New Icons
5. Changed order of three last lines
~6. Shadow of active page is now rounded~
7. Made hyrise symbol larger
~8. Added "Cockpit" name as a photo for nicer font~
~9. Delete Divider (long line) after Views and Settings~
~10. Change "Views" and "Settings" to caps lock~

~Now:~
navbar_2504_hyrisesymbol3

Now: 
navbar_2804

### CODE REVIEW

**Comment by Bouncner** [comment]
I don't think the "System " adds any value. Why is it not a "system overview" as well?

**Comment by Bouncner** [comment]
Maybe we can find a better term for "views", which is more the technical description.

**Comment by Bouncner** [comment]
Further, the palette might crash with the color scheme used to color the metrics. Is it possible to start off with 2-3 colors of the palette, which are clearly distinguishable from the metric colouring?

**Comment by monasobh** [comment]
> I don't think the "System " adds any value. Why is it not a "system overview" as well?

True. What do you think about that? 
naming

**Comment by Bouncner** [comment]
Can you please update the screenshots before anything is merged here?

We have a discussion now in parallel, here and in Slack. We should try to avoid that and only move long discussions to Slack. For short questions as yesterday, please ping Jan and me here on Github.

**Comment by monasobh** [comment]
> Can you please update the screenshots before anything is merged here?
> 
> We have a discussion now in parallel, here and in Slack. We should try to avoid that and only move long discussions to Slack. For short questions as yesterday, please ping Jan and me here on Github.

Ok. What do you and @Bensk1 think about the new navigationbar (see above)? Can we merge it like this?

**Comment by Bensk1** [comment]
Just one question, what does "Added "Cockpit" name as a photo for nicer font" mean? How is the font nicer in a picture?

**Comment by Bouncner** [comment]
Few things.

> Edited space between lines and made them a little shorter

I don't see a reason for that. Why?

> Shadow of active page is now rounded

Why? That's not a button.

> Added "Cockpit" name as a photo for nicer font

I don't think the font is any nicer, nor is it consistent with the rest.

> Change "Views" and "Settings" to caps lock

And again, why? Why do you want to shout at us?

**Comment by monasobh** [comment]
> Just one question, what does "Added "Cockpit" name as a photo for nicer font" mean? How is the font nicer in a picture?

Vue has only limited font styles so I used photoshop to create another font style which I find more suitable for the hyrise logo.

**Comment by Bouncner** [comment]
I think the former one was nicer and it's text. So it should be text, not an image. If it would be a magnificent font, we could discuss if it's worth it. I don't think it's worth it for this font.

**Comment by Bensk1** [comment]
> Vue has only limited font styles so I used photoshop to create another font style which I find more suitable for the hyrise logo.

Does Vue really restrict the fonts that are used? I thought, we could use any browser-supported font, couldn't we? Images might offer more opportunities but the maintainability of text is much better.

**Comment by monasobh** [comment]
> Few things.

>> Edited space between lines and made them a little shorter

> I don't see a reason for that. Why?

According to desing guidelines it's the typical navigationbar size. It's just 2mm shorter than before.

>> Shadow of active page is now rounded

> Why? That's not a button.

What do you mean by that? I don't associate it with a button in a navigationbar. I think it looks nicer shaped. Suits better the shaped border of the metrics.

>> Added "Cockpit" name as a photo for nicer font

> I don't think the font is any nicer, nor is it consistent with the rest.

Ok. I will change it back. Although I think it should be a font that is more like "hyrise" than the text in the navigationbar. Would you agree with that?

>> Change "Views" and "Settings" to caps lock

> And again, why? Why do you want to shout at us?

I can change it back, if you prefer lower case.

Please let me know what else to change back.


MB: sorry, I was drunk and edited this text instead of quoting it.

**Comment by Bensk1** [comment]
> Ok. I will change it back. Although I think it should be a font that is more like "hyrise" than the text in the navigationbar. Would you agree with that?

Sure, if you find a fond that is better suitable and usable via CSS, why not?

**Comment by monasobh** [comment]
> > Vue has only limited font styles so I used photoshop to create another font style which I find more suitable for the hyrise logo.
> 
> Does Vue really restrict the fonts that are used? I thought, we could use any browser-supported font, couldn't we? Images might offer more opportunities but the maintainability of text is much better.

Just the one I used. I agree. I will try to find another one.

**Comment by Bouncner** [comment]
> According to desing guidelines it's the typical navigationbar size. It's just 2mm shorter than before. 

Can you link a PDF of that guideline, please?

> What do you mean by that? I don't associate it with a button in a navigationbar. I think it looks nicer shaped. Suits better the shaped border of the metrics. 

The current design does not show the navigation bar as anything resembling buttons. So why should all of the sudden there be a shadow that looks like the item is a button? I think it's inconsistent with the design of the navigation bar.

> Ok. I will change it back. Although I think it should be a font that is more like "hyrise" than the text in the navigationbar. Would you agree with that? 

I'd say it should rather be exactly the same font (otherwise people will notice and just being "almost" correct is worse than something completely different in my opinion) or just whatever is used as the default font for the whole site.

> I can change it back, if you prefer lower case. 

I'd say yes, revert.

**Comment by monasobh** [comment]
> Can you link a PDF of that guideline, please?

https://material.io/components/navigation-drawer

**Comment by Bouncner** [comment]
That explains a lot. I hate material. It's plain ugly and it hates users.
But fine. I rest my case if that's the guideline you decide to use in the team.

For the font, I'd still take the simple can clean path. Real fonts and text, no uppercase unless there is a reason for that.

**Comment by monasobh** [comment]
>That explains a lot. I hate material. It's plain ugly and it hates users.
But fine. I rest my case if that's the guideline you decide to use in the team.

Can you please send me an example of a navigation bar you like. 

I can change the shadow to not-shaped and add the 2mm again (or even more), if that's what you prefer for the dashboard.

**Comment by Bouncner** [comment]
My personal taste should not block you from implementing a well known design guideline if that guideline is what you decided for in the team.

The things that I don't like have been perfect in the previous version. That's all.

**Comment by monasobh** [comment]
@Bouncner please check again the new screenshot above and let me know if you agree on merging the design like this.

**Comment by Bouncner** [comment]
LGTM.

**Review by kathwill — APPROVED** [review]
Thanks for the changed! Good job

**Pull request merged**
