### PR TITLE
f/639-add-operator-graph

### LINKED ISSUE #639: Show Kruegergraph 2.0 in the frontend
**Is your feature request related to a problem? Please describe:**  
Recently, the `monitor/operator` endpoint has been implemented in the backend. It provides data about the execution time of all operators. Now, we are able to show this data in the frontend.

**Please describe the solution you'd like:**  
Create a Krueger graph for the operator data.
This graph should replace the old graph on the instance comparison. Additionally it should be added to the workload monitoring page as well.

**Please describe alternatives you've considered:**  
Alternatives are welcome.

**Affected Component(s):**  
`Frontend`

**Additional context:**

### PR DESCRIPTION
**Pull request by schTi**
# Resolves #639

**Does your pull request solve a problem? Please describe:**  
This PR adds a new operator krueger graph and replaces the old query type proportion chart on comparison page. The old chart will still remain on the workload monitoring page.

**Affected Component(s):**  
`Frontend`

**Additional context:**  
NOTE: There could be > 20 operators, which makes it really hard to distinguish between those operators. Additionally the colors do not match very well if there are so many operators present. Suggestions on how to solve this are welcome.

image

### CODE REVIEW

**Comment by Bouncner** [comment]
While I don't like hatches: it is possible to use them with your plotting lib?

Otherwise, we could limit the graph to operators with more than 3-5% of the overall execution time. That should limit the graph to few operators for almost all cases.

**Comment by Bouncner** [comment]
Or even: do we maybe want a table instead?

**Comment by Bouncner** [comment]
A sorted table would be my current favorite as I am not able to guess the differences of the three main blocks in your example.

**Comment by Bensk1** [comment]
Or display the percentages with/in/next to the graph?

**Comment by schTi** [comment]
Showing the percentages persistently would be a quick win. A table is also possible, but requires some more work now. What do you prefer?

**Comment by schTi** [comment]
The entries in the graph could also be sorted to improve readability.

**Comment by Bouncner** [comment]
Can you take a look at Fig 1 here: https://hpi.de/plattner/people/phd-students/martin-boissier.html?tx_extbibsonomycsl_publicationlist%5Bcontroller%5D=Document&tx_extbibsonomycsl_publicationlist%5BfileName%5D=ind1437d__camera_ready.pdf&tx_extbibsonomycsl_publicationlist%5BintraHash%5D=067ce22dfc5fe311439343e3ffb62ec4&tx_extbibsonomycsl_publicationlist%5BuserName%5D=import_epic&cHash=954b02f8d287403c600cb8db8159d331

Would it be possible to group all operators with a share of <5% and show their stats in the hover text?

**Comment by schTi** [comment]
> Can you take a look at Fig 1 here: https://hpi.de/plattner/people/phd-students/martin-boissier.html?tx_extbibsonomycsl_publicationlist%5Bcontroller%5D=Document&tx_extbibsonomycsl_publicationlist%5BfileName%5D=ind1437d__camera_ready.pdf&tx_extbibsonomycsl_publicationlist%5BintraHash%5D=067ce22dfc5fe311439343e3ffb62ec4&tx_extbibsonomycsl_publicationlist%5BuserName%5D=import_epic&cHash=954b02f8d287403c600cb8db8159d331
> 
> Would it be possible to group all operators with a share of <5% and show their stats in the hover text?

Yes that should be possible, I'm gonna try this

**Comment by schTi** [comment]
image

Thats how it looks like. All entries smaller than 5 % are being combined to a grey "rest" entry, which will always be placed on top. The other entries are  being stacked highest to lowest. On hover all labels are automatically shown.

Dont mind the labels, Im just working with some fake data.

**Comment by Bouncner** [comment]
Looks good. I think I need to see it live and in action for TPC-H. With the labels (assuming they do not waste too much space and we keep them) you can probably remove the legend.
Further, I'd like to see the overall runtime of each operator.

**Comment by Bouncner** [comment]
Or maybe leave the legend and then have a detailed (incl. aggr. runtime) tooltip when hovering the item with the mouse?

**Comment by schTi** [comment]
I thought about removing the legend, too. It takes up so much space, but Im not sure if its enough to show the name on hover.

**Comment by Bouncner** [comment]
No, I wouldn't remove the legend AND have the names only shown when hovering.
It needs to be one of them.

And since the hovers might get too large when we also show the aggregated runtime, I think a legend + detailed tooltips when hovering might be a good solution. What do you think?

**Comment by schTi** [comment]
We definitely need names for the entry which combines multiple small entries on hover, because otherwise there is no according information in the legend.

What do you think about this one?
image

image

Still no real data, but a more realistic sample

**Comment by Bensk1** [comment]
> We definitely need names for the entry which combines multiple small entries on hover, because otherwise there is no according information in the legend.

Just "Other"?

**Comment by Bouncner** [comment]
I don't like "Operator proportion" ... "Operator Runtime Overview"? "Distribution of Operator Runtimes"

**Comment by schTi** [comment]
image

image

image


Here some examples of real TPCH sf 0.1 data.

**Comment by schTi** [comment]
image

With appropriate time conversion

**Review by MaxSchneider1337 — APPROVED** [review]
nice changes

**Pull request merged**
