### PR TITLE
F/518 improve metrics naming and design

### LINKED ISSUE #518: improve metrics naming and design
**Is your feature request related to a problem? Please describe:**  
y-axes labels look kind of odd.

**Please describe the solution you'd like:**  
will still need to discuss this, maybe we should show them horizontally. 

**Please describe alternatives you've considered:**
we could also just add the label in the chart-title

- [x] change number formatting from 23'300 to 23 300 (only spaceletter)

**Affected Component(s):**  
Frontend

image

image

image
change number formatting from 23'300 to 23 300
image

### PR DESCRIPTION
**Pull request by monasobh**
# Resolves #518

What's new?
1. change number formatting from 23`000 to 23 000
2. add space between Query Type Proportion-title and graph
3. change title names of metrics 
Memory Footprint --> Data Size
RAM --> Process Memory (RSS)
CPU --> CPU Utilization
Storage --> Data Size - Overview
Access Frequency --> Segment Acces Frequencies

- [x] talk to backend to check if new names of metrics are correct

**Affected Component(s):**  
`Frontend`

image
image
image

image

### CODE REVIEW

**Comment by Bouncner** [comment]
Picture?

**Comment by monasobh** [comment]
> Picture?

coming

**Comment by monasobh** [comment]
@Bouncner I also added a picture with a comma seperator, which I would prefer for better readability. What do you think?

**Comment by Bouncner** [comment]
As a german, I am easily confused by having both `,` and `.` in a single graph (or more precise: in the graph and directly above in the current metric). Hence, I'd vote for the space.

@Bensk1 : your opinion?

**Review by schTi — APPROVED** [review]
Good job!

**Pull request merged**
