### PR TITLE
F/529 change color palette

### LINKED ISSUE #529: change colors for databases
**Is your feature request related to a problem? Please describe:**  
The color palette differentiates between light and dark colors. 

**Please describe the solution you'd like:**  
Find a nice color palette with at least 10 colors that are only light.

**Affected Component(s):**  
`Frontend`

Example of differentiating light and dark color: 
cockpit13

New colors: 
cockpit_color4

cockpit_color4_2

Same colors as before:
image

Slightly darker, so one can see the difference of access frequency better:
image

### PR DESCRIPTION
**Pull request by monasobh**
# Resolves #529 

**Does your pull request solve a problem? Please describe:**  

Whats new?
There are now 8 colors especially for databases. The colors of the low, avg, and high metric numbers next to the metric title are different tones of green, orange and red to differentiate between those and the database colors. 

**Colors (only) for databases:**
image
image
image

**New colors for the Kruegergraph:**
image

**New colors for Access Frequency: (They need to be a little bit darker to show differences better)**
access_highitensitiy2

**New colors for the Treemap:**
image

**Affected Component(s):**  
`Frontend`

### CODE REVIEW

**Comment by Bouncner** [comment]
I'd vote to have some form of red and blue for hot and cold data  in the access visualization.

Further, the only palette I like is the one used in the Krueger graph. But that's probably just my taste. Maybe talk about that with all UI people on Monday after the call?

**Comment by monasobh** [comment]
> I'd vote to have some form of red and blue for hot and cold data in the access visualization.
> 
> Further, the only palette I like is the one used in the Krueger graph. But that's probably just my taste. Maybe talk about that with all UI people on Monday after the call?

**Comment by monasobh** [comment]
> I'd vote to have some form of red and blue for hot and cold data in the access visualization.
> 
> Further, the only palette I like is the one used in the Krueger graph. But that's probably just my taste. Maybe talk about that with all UI people on Monday after the call?

**Comment by monasobh** [comment]
@Bouncner @Bensk1 Do you agree with the colors you see above?

**Review by schTi — APPROVED** [review]
good job!

**Pull request merged**
