### PR TITLE
f/687-scroll-plugin-logs

### LINKED ISSUE #687: Change sorting in plugin log
**Is your feature request related to a problem? Please describe:**  
At the moment the log messages in the plugin log are sorted by time in ascending order. Because of that the user needs to scroll to the end of the log to see the current log messages.
PluginLog

**Please describe the solution you'd like:**  
Sorting the plugin log messages in descending order solves the problem.

**Affected Component(s):**  
`Frontend`

### PR DESCRIPTION
**Pull request by schTi**
# Resolves #687

**Does your pull request solve a problem? Please describe:**  
This PR adds auto scrolling to the latest plugin log entry

**Affected Component(s):**  
`Frontend`

### CODE REVIEW

**Review by MaxSchneider1337 — COMMENTED** [review]
how is the performance??? this has to be sorted every second, which seems to be very heavy

I think the array simply has to be reversed

**Comment by MaxSchneider1337** [comment]
> how is the performance??? this has to be sorted every second, which seems to be very heavy
> 
> I think the array simply has to be reversed

maybe use `array.reverse()` or some functionality of the vuetify textbox

**Comment by schTi** [comment]
Can we ensure that those logs are sorted oldest > latest when returned from backend?

**Comment by MaxSchneider1337** [comment]
> Can we ensure that those logs are sorted oldest > latest when returned from backend?

i think so, because the current textbox always shows them oldest to latest. I also think, that this direction (oldest to latest) ist correct. The textbox should auto-scroll to the bottom all the time.

**Comment by MaxSchneider1337** [comment]
> > Can we ensure that those logs are sorted oldest > latest when returned from backend?
> 
> i think so, because the current textbox always shows them oldest to latest. I also think, that this direction (oldest to latest) ist correct. The textbox should auto-scroll to the bottom all the time.

at least that would be my suggestion. Could be much harder to implement

**Comment by schTi** [comment]
> > Can we ensure that those logs are sorted oldest > latest when returned from backend?
> 
> i think so, because the current textbox always shows them oldest to latest. I also think, that this direction (oldest to latest) ist correct. The textbox should auto-scroll to the bottom all the time.

Yeah. Maybe you are right. I will have a look how this would work

**Comment by schTi** [comment]
Added auto scroll to the bottom log entry. If you scroll manually to the top, it will stop.

**Review by MaxSchneider1337 — APPROVED** [review]
Sorry for the additional work, but it looks really nice now

**Pull request merged**
