### PR TITLE
f/496-variable-precision

### LINKED ISSUE #496: implement precision slider
**Is your feature request related to a problem? Please describe:**  
Frontend probably can't show 60 min of linechart-data in real time.

**Please describe the solution you'd like:**  
precision slider to give the backend an interval to aggregate historical data.

**Affected Component(s):**  
Frontend

**Additional context:**  
see salck thread

### PR DESCRIPTION
**Pull request by schTi**
# Resolves #496

**Does your pull request solve a problem? Please describe:**  
This PR adds precision selection.

image

**Affected Component(s):**  
`Frontend`

### CODE REVIEW

**Comment by Bouncner** [comment]
Does it adapt automatically when I change the timespan?

**Comment by schTi** [comment]
> Does it adapt automatically when I change the timespan?

I am not totally sure, what do you mean with automatically adaption. But that are the currently available time ranges:
image

You can always select only aggregation intervals, which are smaller than the time range and at least 1/60 times as big. Which means, when you select a 60 minute range, the smallest aggregation you can select is 1 minute. 
When you change the time range, and the applied aggregation interval is not available any more for this time range, than it will automatically select the smallest available aggregation option.

The available aggregation intervals are:
1s, 5s, 15s, 30s, 1min, 5min

**Comment by Bouncner** [comment]
So when I click the 1h timespan, the interval is automatically changed to 1min?

**Comment by schTi** [comment]
> So when I click the 1h timespan, the interval is automatically changed to 1min?

Yes exactly. But you can still select a 5min aggregation.

**Comment by Bouncner** [comment]
Sounds good!👌

**Review by MaxSchneider1337 — APPROVED** [review]
Looks good to me

**Pull request merged**
