### PR TITLE
B/add real kruegerdata

### LINKED ISSUE #183: Workload Krügergraph should show real data
**Is your feature request related to a problem? Please describe.**
The data for the workload Krügergraph is mocked.

**Describe the solution you'd like**
It should be real data.

**Affected Component**
`Cockpit Backend`, `WorkloadGenerator`

### PR DESCRIPTION
**Pull request by PeterTsayun**
# Resolves #183

**Does your pull request solve a problem? Please describe:**  
Now, we are able to show the real workload data in the kruegergraph (workload_overview).

**Does your pull request add a feature? Please describe:**  
Example of `/monitor/krueger_data` response:
```
[
  {
    "id": "momentum",
    "krueger_data": [
      {
        "query_type": "SELECT",
        "total_latency": 18121695583,
        "total_frequency": 831
      },
      {
        "query_type": "CREATE",
        "total_latency": 286013,
        "total_frequency": 37
      },
      {
        "query_type": "UPDATE",
        "total_latency": 0,
        "total_frequency": 0
      },
      {
        "query_type": "INSERT",
        "total_latency": 0,
        "total_frequency": 0
      },
      {
        "query_type": "DELETE",
        "total_latency": 0,
        "total_frequency": 0
      },
      {
        "query_type": "DROP",
        "total_latency": 51837,
        "total_frequency": 37
      },
      {
        "query_type": "COPY",
        "total_latency": 2994107353,
        "total_frequency": 8
      },
      {
        "query_type": "OTHER",
        "total_latency": 0,
        "total_frequency": 0
      }
    ]
  }
]
```
**Affected Component(s):**  
`App`, `BackgroundScheduler`

**Additional context:**

### CODE REVIEW

**Comment by Bouncner** [comment]
Even though we always call it the "Krüger Graph" and will continue to do so, we should still use correct names in the code/public.
@Bensk1 : 'workload_overview' and 'operators_overview'?

**Review by Alexander-Dubrawski — APPROVED** [review]

**Comment by Bouncner** [comment]
WTF?

**Comment by Bouncner** [comment]
Revert and fix.

**Comment by Bouncner** [comment]
@PeterTsayun

**Comment by PeterTsayun** [comment]
> Revert and fix.

Do you mean to adjust the function names to the 'workload_overview' and 'operators_overview'? Is this name convention final? @Bouncner @Bensk1

**Pull request merged**
