### PR TITLE
Change display of host

### PR DESCRIPTION
**Pull request by Alexander-Dubrawski**
**Does your pull request solve a problem? Please describe:**  
At the comparison, workload, and overview site the hostname was displayed. This was problematic because if the Hyrise instances were running on the same machine no clear visual separation was possible. I changed it so now we see the ID and the host. Please give me feedback if the position of the host is good, or if I should remove it.

Screenshot 2020-09-17 at 18 30 33

### CODE REVIEW

**Comment by Bouncner** [comment]
Too many lines in the header.

Looks like this header is also shown on the overview page. Is that right?

**Comment by Alexander-Dubrawski** [comment]
> Too many lines in the header.
> 
> Looks like this header is also shown on the overview page. Is that right?

Yes and the comparison page. We could use the following alternatives: 

Screenshot 2020-09-17 at 20 08 33

The header on the workload page looks at the moment as follows: 

Screenshot 2020-09-17 at 20 01 55

An alternative could be: 

Screenshot 2020-09-17 at 20 09 27

What do you think? In my opinion, it could still be helpful to see the host if the Hyrise instances are running on different machines. For example, if two Hyrise instances are running on the same machine and another one on a different one.

**Comment by Bouncner** [comment]
I am fine with seeing the host name as a hover to ensure that we don't have these additional lines in the comparison view.
So I guess I like your last post + having the hover.

Everything else looks good to me.

**Comment by Alexander-Dubrawski** [comment]
> I am fine with seeing the host name as a hover to ensure that we don't have these additional lines in the comparison view.
> So I guess I like your last post + having the hover.
> 
> Everything else looks good to me.

So with *hover* you mean when I hover with my mouse over the database id that I get to see the host? Something like in this example: https://vuejs.org/v2/guide/#Declarative-Rendering

Screen Recording 2020-09-18 at 12 29 05

@Bouncner what do you think about these changes?

**Comment by Bensk1** [comment]
I am not sure, but I think that's what @Bouncner means, yes.

**Comment by Bouncner** [comment]
I don't like the question mark icon. A simple mouse pointer is fine.

But that's exactly what I wanted. I don't know if that's really what we want in the long run. But for now there at least one way to find the host without screwing up the UI.

**Comment by Alexander-Dubrawski** [comment]
> I don't like the question mark icon. A simple mouse pointer is fine.
> 
> But that's exactly what I wanted. I don't know if that's really what we want in the long run. But for now there at least one way to find the host without screwing up the UI.

I changed the cursor: 

Screen Recording 2020-10-05 at 15 44 10

@Bouncner are you happy with this implementation?

**Comment by Bouncner** [comment]
Fine with me.

**Review by Bensk1 — APPROVED** [review]

**Pull request merged**
